### ISSUE TITLE
Add retry to avoid concurrent VM provisioning failure (maximum number of simultaneous operations)

### ISSUE THREAD

**Issue by aledsage** [cloudsoft/jclouds-vcloud-director#28]
When deploying 4 VMs concurrently (with 4 separate calls to createNodesInGroup of 1 VM each), one of the VMs failed with the error shown below.

It would be good if we did an exponential backoff and retry when we get this error. It seems that we only got the error when doing concurrent POSTs to create the VMs.

This is with jclouds vcloud-director version 1.9.1-20151021.1122.

```
2015-10-21 21:46:34,962 DEBUG jclouds.headers [user thread 2]: >> POST https://acme.com/api/vdc/dcd952e3-6f07-42dd-b142-fc94b0a55062/action/composeVApp HTTP/1.1
2015-10-21 21:46:34,962 DEBUG jclouds.headers [user thread 2]: >> x-vcloud-authorization: ZXgKW6bavBJprbZdK3hKOk/FO5ik6dZWyPiYSk8T4S8=
2015-10-21 21:46:34,962 DEBUG jclouds.headers [user thread 2]: >> Cookie: vcloud-token=ZXgKW6bavBJprbZdK3hKOk/FO5ik6dZWyPiYSk8T4S8=
2015-10-21 21:46:34,962 DEBUG jclouds.headers [user thread 2]: >> Accept: application/*+xml;version=1.5
2015-10-21 21:46:34,962 DEBUG jclouds.headers [user thread 2]: >> Content-Type: application/vnd.vmware.vcloud.composeVAppParams+xml
2015-10-21 21:46:34,962 DEBUG jclouds.headers [user thread 2]: >> Content-Length: 3201
2015-10-21 21:46:36,123 DEBUG o.j.h.o.OkHttpCommandExecutorService [user thread 2]: Receiving response 2030674488: HTTP/1.1 400 Bad Request
2015-10-21 21:46:36,123 DEBUG jclouds.headers [user thread 2]: << HTTP/1.1 400 Bad Request
2015-10-21 21:46:36,123 DEBUG jclouds.headers [user thread 2]: << Date: Wed, 21 Oct 2015 20:46:34 GMT
2015-10-21 21:46:36,123 DEBUG jclouds.headers [user thread 2]: << Date: Wed, 21 Oct 2015 20:46:36 GMT
2015-10-21 21:46:36,123 DEBUG jclouds.headers [user thread 2]: << OkHttp-Received-Millis: 1445460396123
2015-10-21 21:46:36,123 DEBUG jclouds.headers [user thread 2]: << OkHttp-Selected-Protocol: http/1.1
2015-10-21 21:46:36,123 DEBUG jclouds.headers [user thread 2]: << OkHttp-Sent-Millis: 1445460394964
2015-10-21 21:46:36,123 DEBUG jclouds.headers [user thread 2]: << Set-Cookie: BIGipServer~cmbe_01_de-cpy0-dmz-maz~cmbe_01_vcd-portal-api-ext_443_pool=rd1o00000000000000000000ffffd973440co443; path=/
2015-10-21 21:46:36,124 DEBUG jclouds.headers [user thread 2]: << Vary: Accept-Encoding
2015-10-21 21:46:36,124 DEBUG jclouds.headers [user thread 2]: << Content-Type: application/vnd.vmware.vcloud.error+xml;version=1.5
2015-10-21 21:46:36,124 DEBUG jclouds.headers [user thread 2]: << Content-Length: 472
2015-10-21 21:46:36,124 DEBUG jclouds.wire [user thread 2]: << "<?xml version="1.0" encoding="UTF-8"?>[\n]"
2015-10-21 21:46:36,124 DEBUG jclouds.wire [user thread 2]: << "<Error xmlns="http://www.vmware.com/vcloud/v1.5" minorErrorCode="OPERATION_LIMITS_EXCEEDED" message="The maximum number of simultaneous operations for user &quot;myname&quot; on organization &quot;my-org&quot; has been reached." majorErrorCode="400" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.vmware.com/vcloud/v1.5 http://acme.com/api/v1.5/schema/master.xsd"></Error>[\n]"
2015-10-21 21:46:36,136 ERROR jclouds.compute [user thread 4]: createNodesInGroup(brooklyn-nwl885-amp-auto-qa-n9ab-mongodb-server-gsey), completed: 0/1, errors: 1, rate: 3580ms/op
java.util.concurrent.ExecutionException: org.jclouds.vcloud.director.v1_5.VCloudDirectorException: Operation Limits Exceeded (400) Error: The maximum number of simultaneous operations for user "myname" on organization "my-org" has been reached.
        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299) ~[guava-16.0.1.jar:na]
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286) ~[guava-16.0.1.jar:na]
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116) ~[guava-16.0.1.jar:na]
        at org.jclouds.concurrent.FutureIterables$1.run(FutureIterables.java:123) ~[jclouds-core-1.9.1.jar:1.9.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: org.jclouds.vcloud.director.v1_5.VCloudDirectorException: Operation Limits Exceeded (400) Error: The maximum number of simultaneous operations for user "myname" on organization "my-org" has been reached.
        at org.jclouds.vcloud.director.v1_5.handlers.VCloudDirectorErrorHandler.handleError(VCloudDirectorErrorHandler.java:58) ~[vcloud-director-1.9.1-20151021.1122.jar:1.9.1-20151021.1122]
        at org.jclouds.http.handlers.DelegatingErrorHandler.handleError(DelegatingErrorHandler.java:65) ~[jclouds-core-1.9.1.jar:1.9.1]
        at org.jclouds.http.internal.BaseHttpCommandExecutorService.shouldContinue(BaseHttpCommandExecutorService.java:136) ~[jclouds-core-1.9.1.jar:1.9.1]
        at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:105) ~[jclouds-core-1.9.1.jar:1.9.1]
        at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:90) ~[jclouds-core-1.9.1.jar:1.9.1]
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:73) ~[jclouds-core-1.9.1.jar:1.9.1]
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:44) ~[jclouds-core-1.9.1.jar:1.9.1]
        at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117) ~[jclouds-core-1.9.1.jar:1.9.1]
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) ~[guava-16.0.1.jar:na]
        at com.sun.proxy.$Proxy227.composeVApp(Unknown Source) ~[na:na]
        at org.jclouds.vcloud.director.v1_5.compute.strategy.VCloudDirectorComputeServiceAdapter.createNodeWithGroupEncodedIntoName(VCloudDirectorComputeServiceAdapter.java:175) ~[vcloud-director-1.9.1-20151021.1122.jar:1.9.1-20151021.1122]
        at org.jclouds.compute.strategy.impl.AdaptingComputeServiceStrategies.createNodeWithGroupEncodedIntoName(AdaptingComputeServiceStrategies.java:195) ~[jclouds-compute-1.9.1.jar:1.9.1]
        at org.jclouds.compute.strategy.impl.CreateNodesWithGroupEncodedIntoNameThenAddToSet$AddNode.call(CreateNodesWithGroupEncodedIntoNameThenAddToSet.java:79) ~[jclouds-compute-1.9.1.jar:1.9.1]
        at org.jclouds.compute.strategy.impl.CreateNodesWithGroupEncodedIntoNameThenAddToSet$AddNode.call(CreateNodesWithGroupEncodedIntoNameThenAddToSet.java:63) ~[jclouds-compute-1.9.1.jar:1.9.1]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[na:1.7.0_71]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
        at java.lang.Thread.getStackTrace(Thread.java:1589) [na:1.7.0_71]
        at org.jclouds.compute.strategy.impl.CreateNodesWithGroupEncodedIntoNameThenAddToSet.createNodeInGroupWithNameAndTemplate(CreateNodesWithGroupEncodedIntoNameThenAddToSet.java:167) ~[jclouds-compute-1.9.1.jar:1.9.1]
        at org.jclouds.compute.strategy.impl.CreateNodesWithGroupEncodedIntoNameThenAddToSet.execute(CreateNodesWithGroupEncodedIntoNameThenAddToSet.java:122) ~[jclouds-compute-1.9.1.jar:1.9.1]
        at org.jclouds.compute.internal.BaseComputeService.createNodesInGroup(BaseComputeService.java:210) ~[jclouds-compute-1.9.1.jar:1.9.1]
        at org.apache.brooklyn.location.jclouds.JcloudsLocation.obtainOnce(JcloudsLocation.java:711) ~[patch-jcloudsLocation-20151021.2045.jar:na]
        at org.apache.brooklyn.location.jclouds.JcloudsLocation.obtain(JcloudsLocation.java:606) ~[patch-jcloudsLocation-20151021.2045.jar:na]
        at brooklyn.networking.portforwarding.subnet.JcloudsPortforwardingSubnetLocation.obtain(JcloudsPortforwardingSubnetLocation.java:121) ~[brooklyn-networking-portforwarding-0.9.0-20151021.1332.jar:0.9.0-20151021.1332]
        at brooklyn.networking.portforwarding.subnet.JcloudsPortforwardingSubnetLocation.obtain(JcloudsPortforwardingSubnetLocation.java:59) ~[brooklyn-networking-portforwarding-0.9.0-20151021.1332.jar:0.9.0-20151021.1332]
        at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$ObtainLocationTask.call(MachineLifecycleEffectorTasks.java:406) ~[brooklyn-software-base-0.9.0-20151021.1332.jar:0.9.0-20151021.1332]
        at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$ObtainLocationTask.call(MachineLifecycleEffectorTasks.java:396) ~[brooklyn-software-base-0.9.0-20151021.1332.jar:0.9.0-20151021.1332]
        at org.apache.brooklyn.util.core.task.Tasks.withBlockingDetails(Tasks.java:98) ~[brooklyn-core-0.9.0-20151021.1332.jar:0.9.0-20151021.1332]
        at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$ProvisionMachineTask.call(MachineLifecycleEffectorTasks.java:380) ~[brooklyn-software-base-0.9.0-20151021.1332.jar:0.9.0-20151021.1332]
        at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$ProvisionMachineTask.call(MachineLifecycleEffectorTasks.java:364) ~[brooklyn-software-base-0.9.0-20151021.1332.jar:0.9.0-20151021.1332]
        at org.apache.brooklyn.util.core.task.DynamicSequentialTask$DstJob.call(DynamicSequentialTask.java:342) ~[brooklyn-core-0.9.0-20151021.1332.jar:0.9.0-20151021.1332]
        at org.apache.brooklyn.util.core.task.BasicExecutionManager$SubmissionCallable.call(BasicExecutionManager.java:468) ~[brooklyn-core-0.9.0-20151021.1332.jar:0.9.0-20151021.1332]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[na:1.7.0_71]
        ... 3 common frames omitted
2015-10-21 21:46:36,145 ERROR jclouds.compute [brooklyn-execmanager-xRlj22lS-442]: createNodesInGroup(brooklyn-nwl885-amp-auto-qa-n9ab-mongodb-server-gsey), completed: 0/1, errors: 1, rate: 3588ms/op
java.lang.RuntimeException: createNodesInGroup(brooklyn-nwl885-amp-auto-qa-n9ab-mongodb-server-gsey), completed: 0/1, errors: 1, rate: 3588ms/op
        at org.jclouds.concurrent.FutureIterables.awaitCompletion(FutureIterables.java:153) ~[jclouds-core-1.9.1.jar:1.9.1]
        at org.jclouds.compute.internal.BaseComputeService.createNodesInGroup(BaseComputeService.java:214) [jclouds-compute-1.9.1.jar:1.9.1]
        at org.apache.brooklyn.location.jclouds.JcloudsLocation.obtainOnce(JcloudsLocation.java:711) [patch-jcloudsLocation-20151021.2045.jar:na]
        at org.apache.brooklyn.location.jclouds.JcloudsLocation.obtain(JcloudsLocation.java:606) [patch-jcloudsLocation-20151021.2045.jar:na]
        at brooklyn.networking.portforwarding.subnet.JcloudsPortforwardingSubnetLocation.obtain(JcloudsPortforwardingSubnetLocation.java:121) [brooklyn-networking-portforwarding-0.9.0-20151021.1332.jar:0.9.0-20151021.1332]
        at brooklyn.networking.portforwarding.subnet.JcloudsPortforwardingSubnetLocation.obtain(JcloudsPortforwardingSubnetLocation.java:59) [brooklyn-networking-portforwarding-0.9.0-20151021.1332.jar:0.9.0-20151021.1332]
        at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$ObtainLocationTask.call(MachineLifecycleEffectorTasks.java:406) [brooklyn-software-base-0.9.0-20151021.1332.jar:0.9.0-20151021.1332]
        at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$ObtainLocationTask.call(MachineLifecycleEffectorTasks.java:396) [brooklyn-software-base-0.9.0-20151021.1332.jar:0.9.0-20151021.1332]
        at org.apache.brooklyn.util.core.task.Tasks.withBlockingDetails(Tasks.java:98) [brooklyn-core-0.9.0-20151021.1332.jar:0.9.0-20151021.1332]
        at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$ProvisionMachineTask.call(MachineLifecycleEffectorTasks.java:380) [brooklyn-software-base-0.9.0-20151021.1332.jar:0.9.0-20151021.1332]
        at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$ProvisionMachineTask.call(MachineLifecycleEffectorTasks.java:364) [brooklyn-software-base-0.9.0-20151021.1332.jar:0.9.0-20151021.1332]
        at org.apache.brooklyn.util.core.task.DynamicSequentialTask$DstJob.call(DynamicSequentialTask.java:342) [brooklyn-core-0.9.0-20151021.1332.jar:0.9.0-20151021.1332]
        at org.apache.brooklyn.util.core.task.BasicExecutionManager$SubmissionCallable.call(BasicExecutionManager.java:468) [brooklyn-core-0.9.0-20151021.1332.jar:0.9.0-20151021.1332]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_71]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
```

**Comment by aledsage** [comment]
I wonder if this is more likely since PR #25 was merged.

Did that change our getImages to be more efficient, so it will only look up the images once (rather than once per call to `createNodesInGroup`)? For listing vApp instances - even though it seems to be done once per `createNodesInGroup`, could that be more in lock-step than previously so all our concurrent calls get to the VM provisioning at exactly the same time?

If that were true, we might be more likely to hit the "Operation Limits Exceeded" than if the threads all got to that point at different times.

But that is wild speculation.

**Comment by aledsage** [comment]
Fixed with exponential backoff and retry.
