### ISSUE TITLE
NullPointerException on destroyNode (retrieved VM was null because of "403 Forbidden")

### ISSUE THREAD

**Issue by aledsage** [cloudsoft/jclouds-vcloud-director#29]
When stopping an app in vCloud Director, I hit the `NullPointerException` shown below.

This was with version 1.9.1-20151022.1606

The call immediately before the NPE returned a `403 Forbidden` for `GET https://acme.com/api/vApp/vm-b7b8c2fe-1083-4b79-aa4f-1f91fd68d548`.

One possibility is that someone had deleted the VM manually through vCloud Director's web-console, prior to `destroyNode` being called. However, we can't be certain of this.

```
2015-10-23 16:16:14,083 ERROR o.a.b.l.j.JcloudsLocation [brooklyn-execmanager-WmzCXEs5-9697]: Problem releasing machine SshMachineLocation[Acme 2.0 ABC006:129.185.160.37/129.185.160.37:11091@exXplkzL] in JcloudsPortforwardingSubnetLocation[Acme 2.0 ABC006:cloudsoft@ctd-emea01/vcloud-director:https://acme.com/api/vdc/dcd952e3-6f07-42dd-b142-fc94b0a55062:https://acme.com/api@hLH3NDWJ], instance id urn:vcloud:vm:b7b8c2fe-1083-4b79-aa4f-1f91fd68d548; ignoring and continuing, will throw subsequently: java.lang.NullPointerException
java.lang.NullPointerException: null
        at org.jclouds.vcloud.director.v1_5.compute.util.VCloudDirectorComputeUtils.getVAppParent(VCloudDirectorComputeUtils.java:178) ~[vcloud-director-1.9.1-20151022.1606.jar:1.9.1-20151022.1606]
        at org.jclouds.vcloud.director.v1_5.compute.strategy.VCloudDirectorComputeServiceAdapter.destroyNode(VCloudDirectorComputeServiceAdapter.java:475) ~[vcloud-director-1.9.1-20151022.1606.jar:1.9.1-20151022.1606]
        at org.jclouds.compute.strategy.impl.AdaptingComputeServiceStrategies.destroyNode(AdaptingComputeServiceStrategies.java:181) ~[jclouds-compute-1.9.1.jar:1.9.1]
        at org.jclouds.compute.internal.BaseComputeService$2.apply(BaseComputeService.java:291) ~[jclouds-compute-1.9.1.jar:1.9.1]
        at org.jclouds.compute.internal.BaseComputeService$2.apply(BaseComputeService.java:288) ~[jclouds-compute-1.9.1.jar:1.9.1]
        at org.jclouds.util.Predicates2$RetryablePredicate.apply(Predicates2.java:117) ~[jclouds-core-1.9.1.jar:1.9.1]
        at org.jclouds.compute.internal.BaseComputeService.doDestroyNode(BaseComputeService.java:302) ~[jclouds-compute-1.9.1.jar:1.9.1]
        at org.jclouds.compute.internal.BaseComputeService.destroyNode(BaseComputeService.java:243) ~[jclouds-compute-1.9.1.jar:1.9.1]
        at org.apache.brooklyn.location.jclouds.JcloudsLocation.releaseNode(JcloudsLocation.java:2369) ~[brooklyn-locations-jclouds-0.9.0-20151023.0054.jar:0.9.0-20151023.0054]
        at org.apache.brooklyn.location.jclouds.JcloudsLocation.release(JcloudsLocation.java:2319) ~[brooklyn-locations-jclouds-0.9.0-20151023.0054.jar:0.9.0-20151023.0054]
        at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks.stopAnyProvisionedMachines(MachineLifecycleEffectorTasks.java:912) [brooklyn-software-base-0.9.0-20151023.0054.jar:0.9.0-20151023.0054]
        at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$StopAnyProvisionedMachinesTask.call(MachineLifecycleEffectorTasks.java:777) [brooklyn-software-base-0.9.0-20151023.0054.jar:0.9.0-20151023.0054]
        at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$StopAnyProvisionedMachinesTask.call(MachineLifecycleEffectorTasks.java:775) [brooklyn-software-base-0.9.0-20151023.0054.jar:0.9.0-20151023.0054]
        at org.apache.brooklyn.util.core.task.DynamicSequentialTask$DstJob.call(DynamicSequentialTask.java:342) [brooklyn-core-0.9.0-20151023.0054.jar:0.9.0-20151023.0054]
        at org.apache.brooklyn.util.core.task.BasicExecutionManager$SubmissionCallable.call(BasicExecutionManager.java:468) [brooklyn-core-0.9.0-20151023.0054.jar:0.9.0-20151023.0054]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_71]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
```

Some log snippets, showing the HTTP requests sent prior to the error, are shown below:

```
2015-10-23 16:16:10,268 DEBUG jclouds.compute [brooklyn-execmanager-WmzCXEs5-9697]: >> destroying node(urn:vcloud:vm:b7b8c2fe-1083-4b79-aa4f-1f91fd68d548)
2015-10-23 16:16:10,270 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: >> GET https://acme.com/api/entity/urn:vcloud:vm:b7b8c2fe-1083-4b79-aa4f-1f91fd68d548 HTTP/1.1
2015-10-23 16:16:11,099 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: >> GET https://acme.com/api/vApp/vm-b7b8c2fe-1083-4b79-aa4f-1f91fd68d548 HTTP/1.1
2015-10-23 16:16:12,663 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: >> GET https://acme.com/api/vApp/vapp-25502a1d-ff64-49a8-8a2f-599cb035bf43 HTTP/1.1
2015-10-23 16:16:13,746 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: >> GET https://acme.com/api/vApp/vm-b7b8c2fe-1083-4b79-aa4f-1f91fd68d548 HTTP/1.1
2015-10-23 16:16:14,083 ERROR o.a.b.l.j.JcloudsLocation [brooklyn-execmanager-WmzCXEs5-9697]: Problem releasing machine SshMachineLocation[Acme 2.0 ABC006:129.185.160.37/129.185.160.37:11091@exXplkzL] in JcloudsPortforwardingSubnetLocation[Acme 2.0 CTD006:cloudsoft@ctd-emea01/vcloud-director:https://acme.com/api/vdc/dcd952e3-6f07-42dd-b142-fc94b0a55062:https://acme.com/api@hLH3NDWJ], instance id urn:vcloud:vm:b7b8c2fe-1083-4b79-aa4f-1f91fd68d548; ignoring and continuing, will throw subsequently: java.lang.NullPointerException
```

And details of the last two requests. Note the `403 Forbidden` for the last one:

```
2015-10-23 16:16:12,662 DEBUG o.j.r.i.InvokeHttpMethod [brooklyn-execmanager-WmzCXEs5-9697]: >> invoking VAppApi.get
2015-10-23 16:16:12,663 DEBUG o.j.h.o.OkHttpCommandExecutorService [brooklyn-execmanager-WmzCXEs5-9697]: Sending request 971343334: GET https://acme.com/api/vApp/vapp-25502a1d-ff64-49a8-8a2f-599cb035bf43 HTTP/1.1
2015-10-23 16:16:12,663 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: >> GET https://acme.com/api/vApp/vapp-25502a1d-ff64-49a8-8a2f-599cb035bf43 HTTP/1.1
2015-10-23 16:16:12,663 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: >> x-vcloud-authorization: zdPrZBXu3C5qQoJbdIwqO0ybxJi+5b4cFuFD1+IqPWk=
2015-10-23 16:16:12,663 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: >> Cookie: vcloud-token=zdPrZBXu3C5qQoJbdIwqO0ybxJi+5b4cFuFD1+IqPWk=
2015-10-23 16:16:12,663 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: >> Accept: application/*+xml;version=1.5

2015-10-23 16:16:13,606 DEBUG o.j.h.o.OkHttpCommandExecutorService [brooklyn-execmanager-WmzCXEs5-9697]: Receiving response 971343334: HTTP/1.1 200 OK
2015-10-23 16:16:13,606 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: << HTTP/1.1 200 OK
2015-10-23 16:16:13,606 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: << Date: Fri, 23 Oct 2015 15:16:12 GMT
2015-10-23 16:16:13,606 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: << Date: Fri, 23 Oct 2015 15:16:13 GMT
2015-10-23 16:16:13,606 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: << OkHttp-Received-Millis: 1445613373606
2015-10-23 16:16:13,606 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: << OkHttp-Selected-Protocol: http/1.1
2015-10-23 16:16:13,606 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: << OkHttp-Sent-Millis: 1445613372663
2015-10-23 16:16:13,606 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: << Set-Cookie: BIGipServer~cmbe_01_de-cpy0-dmz-maz~cmbe_01_vcd-portal-api-ext_443_pool=rd1o00000000000000000000ffffd973440bo443; path=/
2015-10-23 16:16:13,606 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: << Vary: Accept-Encoding
2015-10-23 16:16:13,606 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: << Content-Type: application/vnd.vmware.vcloud.vApp+xml;version=1.5
2015-10-23 16:16:13,606 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "<?xml version="1.0" encoding="UTF-8"?>[\n]"
2015-10-23 16:16:13,606 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "<VApp xmlns="http://www.vmware.com/vcloud/v1.5" ovfDescriptorUploaded="true" deployed="false" status="0" name="brooklyn-nwogww-amp-auto-qa-tomcat-m4ii-tomcat-xkr5-ee8" id="urn:vcloud:vapp:25502a1d-ff64-49a8-8a2f-599cb035bf43" type="application/vnd.vmware.vcloud.vApp+xml" href="https://acme.com/api/vApp/vapp-25502a1d-ff64-49a8-8a2f-599cb035bf43" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.vmware.com/vcloud/v1.5 http://acme.com/api/v1.5/schema/master.xsd">[\n]"
2015-10-23 16:16:13,606 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "    <Link rel="down" type="application/vnd.vmware.vcloud.vAppNetwork+xml" name="Deployment_Network_006" href="https://acme.com/api/network/9bd64c4e-353f-4685-a254-c1bdf672d23c"/>[\n]"
2015-10-23 16:16:13,606 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "    <Link rel="down" type="application/vnd.vmware.vcloud.controlAccess+xml" href="https://acme.com/api/vApp/vapp-25502a1d-ff64-49a8-8a2f-599cb035bf43/controlAccess/"/>[\n]"
2015-10-23 16:16:13,606 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "    <Link rel="up" type="application/vnd.vmware.vcloud.vdc+xml" href="https://acme.com/api/vdc/dcd952e3-6f07-42dd-b142-fc94b0a55062"/>[\n]"
2015-10-23 16:16:13,606 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "    <Link rel="down" type="application/vnd.vmware.vcloud.owner+xml" href="https://acme.com/api/vApp/vapp-25502a1d-ff64-49a8-8a2f-599cb035bf43/owner"/>[\n]"
2015-10-23 16:16:13,606 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "    <Link rel="down" type="application/vnd.vmware.vcloud.metadata+xml" href="https://acme.com/api/vApp/vapp-25502a1d-ff64-49a8-8a2f-599cb035bf43/metadata"/>[\n]"
2015-10-23 16:16:13,606 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "    <Link rel="add" type="application/vnd.emc.vcp.adhocBackupParams+xml" href="https://acme.com/api/vApp/vapp-25502a1d-ff64-49a8-8a2f-599cb035bf43/backups"/>[\n]"
2015-10-23 16:16:13,606 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "    <Link rel="down" type="application/vnd.emc.vcp.adhocBackupParams+xml" href="https://acme.com/api/vApp/vapp-25502a1d-ff64-49a8-8a2f-599cb035bf43/backups"/>[\n]"
2015-10-23 16:16:13,606 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "    <Tasks>[\n]"
2015-10-23 16:16:13,606 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "        <Task status="running" startTime="2015-10-23T17:16:11.183+02:00" operationName="vdcDeleteVapp" operation="Deleting Virtual Application brooklyn-nwogww-amp-auto-qa-tomcat-m4ii-tomcat-xkr5-ee8(25502a1d-ff64-49a8-8a2f-599cb035bf43)" expiryTime="2016-01-21T17:16:11.183+01:00" name="task" id="urn:vcloud:task:494941a0-259e-4cc1-98b0-891c0616e3ea" type="application/vnd.vmware.vcloud.task+xml" href="https://acme.com/api/task/494941a0-259e-4cc1-98b0-891c0616e3ea">[\n]"
2015-10-23 16:16:13,606 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "            <Link rel="task:cancel" href="https://acme.com/api/task/494941a0-259e-4cc1-98b0-891c0616e3ea/action/cancel"/>[\n]"
2015-10-23 16:16:13,606 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "            <Owner type="application/vnd.vmware.vcloud.vApp+xml" name="brooklyn-nwogww-amp-auto-qa-tomcat-m4ii-tomcat-xkr5-ee8" href="https://acme.com/api/vApp/vapp-25502a1d-ff64-49a8-8a2f-599cb035bf43"/>[\n]"
2015-10-23 16:16:13,607 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "            <User type="application/vnd.vmware.admin.user+xml" name="cloudsoft" href="https://acme.com/api/admin/user/22565175-b8e6-46b6-95c8-b81bf3a5e373"/>[\n]"
2015-10-23 16:16:13,607 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "            <Organization type="application/vnd.vmware.vcloud.org+xml" name="ctd-emea01" href="https://acme.com/api/org/93fe563b-52ff-45a3-97ea-44b38686f064"/>[\n]"
2015-10-23 16:16:13,607 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "        </Task>[\n]"
2015-10-23 16:16:13,607 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "    </Tasks>[\n]"
2015-10-23 16:16:13,607 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "    <Owner type="application/vnd.vmware.vcloud.owner+xml">[\n]"
2015-10-23 16:16:13,607 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "        <User type="application/vnd.vmware.admin.user+xml" name="cloudsoft" href="https://acme.com/api/admin/user/22565175-b8e6-46b6-95c8-b81bf3a5e373"/>[\n]"
2015-10-23 16:16:13,607 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "    </Owner>[\n]"
2015-10-23 16:16:13,607 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "    <InMaintenanceMode>false</InMaintenanceMode>[\n]"
2015-10-23 16:16:13,607 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "</VApp>[\n]"

2015-10-23 16:16:13,746 DEBUG o.j.h.o.OkHttpCommandExecutorService [brooklyn-execmanager-WmzCXEs5-9697]: Sending request 485226967: GET https://acme.com/api/vApp/vm-b7b8c2fe-1083-4b79-aa4f-1f91fd68d548 HTTP/1.1
2015-10-23 16:16:13,746 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: >> GET https://acme.com/api/vApp/vm-b7b8c2fe-1083-4b79-aa4f-1f91fd68d548 HTTP/1.1
2015-10-23 16:16:13,746 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: >> x-vcloud-authorization: zdPrZBXu3C5qQoJbdIwqO0ybxJi+5b4cFuFD1+IqPWk=
2015-10-23 16:16:13,746 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: >> Cookie: vcloud-token=zdPrZBXu3C5qQoJbdIwqO0ybxJi+5b4cFuFD1+IqPWk=
2015-10-23 16:16:13,746 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: >> Accept: application/*+xml;version=1.5

2015-10-23 16:16:14,058 DEBUG o.j.h.o.OkHttpCommandExecutorService [brooklyn-execmanager-WmzCXEs5-9697]: Receiving response 485226967: HTTP/1.1 403 Forbidden
2015-10-23 16:16:14,058 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: << HTTP/1.1 403 Forbidden
2015-10-23 16:16:14,058 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: << Date: Fri, 23 Oct 2015 15:16:13 GMT
2015-10-23 16:16:14,058 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: << Date: Fri, 23 Oct 2015 15:16:13 GMT
2015-10-23 16:16:14,058 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: << OkHttp-Received-Millis: 1445613374057
2015-10-23 16:16:14,058 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: << OkHttp-Selected-Protocol: http/1.1
2015-10-23 16:16:14,058 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: << OkHttp-Sent-Millis: 1445613373746
2015-10-23 16:16:14,058 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: << Set-Cookie: BIGipServer~cmbe_01_de-cpy0-dmz-maz~cmbe_01_vcd-portal-api-ext_443_pool=rd1o00000000000000000000ffffd973440bo443; path=/
2015-10-23 16:16:14,058 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: << Vary: Accept-Encoding
2015-10-23 16:16:14,058 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: << Content-Type: application/vnd.vmware.vcloud.error+xml;version=1.5
2015-10-23 16:16:14,058 DEBUG jclouds.headers [brooklyn-execmanager-WmzCXEs5-9697]: << Content-Length: 442
2015-10-23 16:16:14,058 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "<?xml version="1.0" encoding="UTF-8"?>[\n]"
2015-10-23 16:16:14,058 DEBUG jclouds.wire [brooklyn-execmanager-WmzCXEs5-9697]: << "<Error xmlns="http://www.vmware.com/vcloud/v1.5" minorErrorCode="ACCESS_TO_RESOURCE_IS_FORBIDDEN" message="No access to entity &quot;com.vmware.vcloud.entity.vm:b7b8c2fe-1083-4b79-aa4f-1f91fd68d548&quot;." majorErrorCode="403" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.vmware.com/vcloud/v1.5 http://acme.com/api/v1.5/schema/master.xsd"></Error>[\n]"
```

**Comment by bostko** [comment]
@aledsage I tried stopping an App deployed on vcloud director but it stops with no exceptions in the debug log.

**Comment by aledsage** [comment]
Presuming this is a similar race to that in https://github.com/cloudsoft/jclouds-vcloud-director/issues/35

If we begin to delete the VM, then it is deleted behind our backs, and then we try to retrieve the VM object or the vApp object, then we'll get null and throw an NPE. Therefore guard against that - just log and return.

**Comment by aledsage** [comment]
Fixed in https://github.com/cloudsoft/jclouds-vcloud-director/pull/37
