### ISSUE TITLE
NullPointerException trying to provision VM (retrieved vApp was null because of "403 Forbidden")

### ISSUE THREAD

**Issue by aledsage** [cloudsoft/jclouds-vcloud-director#35]
When attempting to start a new VM, we got the error shown below (causing the provision request to fail).

This looks similar to https://github.com/cloudsoft/jclouds-vcloud-director/issues/29, including the previous "403 Forbidden" (this time for a `GET https://emea01.acme.com/api/vApp/vapp-ce0c5359-8197-4435-a5aa-4297897cbf7b`).

```
2016-03-01 17:49:24,956 ERROR o.a.b.l.j.JcloudsLocation [brooklyn-execmanager-weBjEa47-4498]: Failed to start VM for vcloud-director:https://emea01.acme.com/api/vdc/
dcd952e3-6f07-42dd-b142-fc94b0a55062:https://emea01.acme.com/api@VanillaWindowsProcessImpl{id=TL2L8Zc4} after 1m 51s (semaphore obtained in 0ms; template built in 1m
 17s;): null
2016-03-01 17:49:24,957 DEBUG o.a.b.l.j.JcloudsLocation [brooklyn-execmanager-weBjEa47-4498]: java.lang.NullPointerException
        at org.jclouds.vcloud.director.v1_5.compute.functions.VmToNodeMetadata.apply(VmToNodeMetadata.java:86)
        at org.jclouds.vcloud.director.v1_5.compute.functions.VmToNodeMetadata.apply(VmToNodeMetadata.java:53)
        at com.google.common.base.Functions$FunctionComposition.apply(Functions.java:216)
        at com.google.common.collect.Iterators$8.transform(Iterators.java:794)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:646)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at com.google.common.collect.Iterators.indexOf(Iterators.java:771)
        at com.google.common.collect.Iterators.any(Iterators.java:679)
        at com.google.common.collect.Iterables.any(Iterables.java:623)
        at org.jclouds.compute.strategy.impl.CreateNodesWithGroupEncodedIntoNameThenAddToSet.getNextNames(CreateNodesWithGroupEncodedIntoNameThenAddToSet.java:197)
        at org.jclouds.compute.strategy.impl.CreateNodesWithGroupEncodedIntoNameThenAddToSet.execute(CreateNodesWithGroupEncodedIntoNameThenAddToSet.java:121)
        at org.jclouds.compute.internal.BaseComputeService.createNodesInGroup(BaseComputeService.java:210)
        at org.apache.brooklyn.location.jclouds.JcloudsLocation.obtainOnce(JcloudsLocation.java:721)
        at org.apache.brooklyn.location.jclouds.JcloudsLocation.obtain(JcloudsLocation.java:611)
        at brooklyn.networking.portforwarding.subnet.JcloudsPortforwardingSubnetLocation.obtain(JcloudsPortforwardingSubnetLocation.java:122)
        at brooklyn.networking.portforwarding.subnet.JcloudsPortforwardingSubnetLocation.obtain(JcloudsPortforwardingSubnetLocation.java:60)
        at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$ObtainLocationTask.call(MachineLifecycleEffectorTasks.java:406)
        at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$ObtainLocationTask.call(MachineLifecycleEffectorTasks.java:396)
        at org.apache.brooklyn.util.core.task.Tasks.withBlockingDetails(Tasks.java:98)
        at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$ProvisionMachineTask.call(MachineLifecycleEffectorTasks.java:380)
        at org.apache.brooklyn.entity.software.base.lifecycle.MachineLifecycleEffectorTasks$ProvisionMachineTask.call(MachineLifecycleEffectorTasks.java:364)
        at org.apache.brooklyn.util.core.task.DynamicSequentialTask$DstJob.call(DynamicSequentialTask.java:359)
        at org.apache.brooklyn.util.core.task.BasicExecutionManager$SubmissionCallable.call(BasicExecutionManager.java:499)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

Immediately before that in the log, it shows:

```
2016-03-01 17:49:24,921 DEBUG jclouds.headers [brooklyn-execmanager-weBjEa47-4498]: >> GET https://emea01.acme.com/api/vApp/vapp-ce0c5359-8197-4435-a5aa-4297897cbf7b
 HTTP/1.1
2016-03-01 17:49:24,921 DEBUG jclouds.headers [brooklyn-execmanager-weBjEa47-4498]: >> x-vcloud-authorization: k0vr4Csc1OVwbdngMrSx58yxMjSX8x78tEjmPkFIAJU=
2016-03-01 17:49:24,921 DEBUG jclouds.headers [brooklyn-execmanager-weBjEa47-4498]: >> Cookie: vcloud-token=k0vr4Csc1OVwbdngMrSx58yxMjSX8x78tEjmPkFIAJU=
2016-03-01 17:49:24,921 DEBUG jclouds.headers [brooklyn-execmanager-weBjEa47-4498]: >> Accept: application/*+xml;version=1.5
2016-03-01 17:49:24,951 DEBUG o.j.h.o.OkHttpCommandExecutorService [brooklyn-execmanager-weBjEa47-4498]: Receiving response -249011686: HTTP/1.1 403 Forbidden
2016-03-01 17:49:24,951 DEBUG jclouds.headers [brooklyn-execmanager-weBjEa47-4498]: << HTTP/1.1 403 Forbidden
2016-03-01 17:49:24,951 DEBUG jclouds.headers [brooklyn-execmanager-weBjEa47-4498]: << Date: Tue, 01 Mar 2016 17:49:27 GMT
2016-03-01 17:49:24,951 DEBUG jclouds.headers [brooklyn-execmanager-weBjEa47-4498]: << Date: Tue, 01 Mar 2016 17:49:27 GMT
2016-03-01 17:49:24,952 DEBUG jclouds.headers [brooklyn-execmanager-weBjEa47-4498]: << OkHttp-Received-Millis: 1456854564951
2016-03-01 17:49:24,952 DEBUG jclouds.headers [brooklyn-execmanager-weBjEa47-4498]: << OkHttp-Selected-Protocol: http/1.1
2016-03-01 17:49:24,952 DEBUG jclouds.headers [brooklyn-execmanager-weBjEa47-4498]: << OkHttp-Sent-Millis: 1456854564921
2016-03-01 17:49:24,952 DEBUG jclouds.headers [brooklyn-execmanager-weBjEa47-4498]: << Set-Cookie: BIGipServer~cmbe_01_de-cpy0-dmz-maz~cmbe_01_vcd-portal-api-ext_443_pool=rd1o00000000000000000000ffffd973440co443; path=/
2016-03-01 17:49:24,952 DEBUG jclouds.headers [brooklyn-execmanager-weBjEa47-4498]: << Vary: Accept-Encoding
2016-03-01 17:49:24,952 DEBUG jclouds.headers [brooklyn-execmanager-weBjEa47-4498]: << Content-Type: application/vnd.vmware.vcloud.error+xml;version=1.5
2016-03-01 17:49:24,952 DEBUG jclouds.headers [brooklyn-execmanager-weBjEa47-4498]: << Content-Length: 444
2016-03-01 17:49:24,952 DEBUG jclouds.wire [brooklyn-execmanager-weBjEa47-4498]: << "<?xml version="1.0" encoding="UTF-8"?>[\n]"
2016-03-01 17:49:24,952 DEBUG jclouds.wire [brooklyn-execmanager-weBjEa47-4498]: << "<Error xmlns="http://www.vmware.com/vcloud/v1.5" minorErrorCode="ACCESS_TO_RESOURCE_IS_F
```

**Comment by aledsage** [comment]
Interestingly there were two concurrent provision requests being executed in Brooklyn, so two separate threads were attempting to retrieve the vApp listing. Both failed with the same "403 Forbidden" executing GET on the same vApp id. These happened within 2 seconds of each other.

11 seconds earlier in the log, there is an undeploy of that vApp! This confirms the suspicion described in https://github.com/cloudsoft/jclouds-vcloud-director/issues/29, that it can be caused by "someone had deleted the VM".

```
2016-03-01 17:49:13,194 DEBUG o.j.h.o.OkHttpCommandExecutorService [brooklyn-execmanager-weBjEa47-4480]: Sending request 1983343395: POST https://emea01.acme.com/api
/vApp/vapp-ce0c5359-8197-4435-a5aa-4297897cbf7b/action/undeploy HTTP/1.1
2016-03-01 17:49:13,194 DEBUG jclouds.wire [brooklyn-execmanager-weBjEa47-4480]: >> "<?xml version="1.0" encoding="UTF-8" standalone="yes"?>[\n]"
2016-03-01 17:49:13,194 DEBUG jclouds.wire [brooklyn-execmanager-weBjEa47-4480]: >> "<UndeployVAppParams xmlns="http://www.vmware.com/vcloud/v1.5">[\n]"
2016-03-01 17:49:13,194 DEBUG jclouds.wire [brooklyn-execmanager-weBjEa47-4480]: >> "    <UndeployPowerAction>powerOff</UndeployPowerAction>[\n]"
2016-03-01 17:49:13,194 DEBUG jclouds.wire [brooklyn-execmanager-weBjEa47-4480]: >> "</UndeployVAppParams>[\n]"
2016-03-01 17:49:13,194 DEBUG jclouds.headers [brooklyn-execmanager-weBjEa47-4480]: >> POST https://emea01.acme.com/api/vApp/vapp-ce0c5359-8197-4435-a5aa-4297897cbf7
b/action/undeploy HTTP/1.1
2016-03-01 17:49:13,194 DEBUG jclouds.headers [brooklyn-execmanager-weBjEa47-4480]: >> x-vcloud-authorization: k0vr4Csc1OVwbdngMrSx58yxMjSX8x78tEjmPkFIAJU=
2016-03-01 17:49:13,194 DEBUG jclouds.headers [brooklyn-execmanager-weBjEa47-4480]: >> Cookie: vcloud-token=k0vr4Csc1OVwbdngMrSx58yxMjSX8x78tEjmPkFIAJU=
2016-03-01 17:49:13,194 DEBUG jclouds.headers [brooklyn-execmanager-weBjEa47-4480]: >> Accept: application/*+xml;version=1.5
2016-03-01 17:49:13,194 DEBUG jclouds.headers [brooklyn-execmanager-weBjEa47-4480]: >> Content-Type: application/vnd.vmware.vcloud.undeployVAppParams+xml
2016-03-01 17:49:13,194 DEBUG jclouds.headers [brooklyn-execmanager-weBjEa47-4480]: >> Content-Length: 197
```

**Comment by aledsage** [comment]
Fixed in https://github.com/cloudsoft/jclouds-vcloud-director/pull/37
